import argparse
import zipfile
from pathlib import Path


def parse_summary(summary_path: Path) -> dict[str, str]:
    values = {}
    for line in summary_path.read_text(encoding="utf-8").splitlines():
        if ":" not in line:
            continue
        key, value = line.split(":", 1)
        values[key.strip()] = value.strip()
    return values


def update_docx(docx_path: Path, values: dict[str, str]) -> None:
    with zipfile.ZipFile(docx_path, "r") as zin:
        files = {name: zin.read(name) for name in zin.namelist()}

    xml = files["word/document.xml"].decode("utf-8", errors="ignore")
    auto_values = [
        values['Original duration (s)'],
        values['Shortened duration (s)'],
        values['Removed duration (s)'],
        values['Compression ratio (%)'],
    ]

    for replacement in auto_values:
        xml = xml.replace('[AUTO FROM SCRIPT]', replacement, 1)

    files["word/document.xml"] = xml.encode("utf-8")
    with zipfile.ZipFile(docx_path, "w", zipfile.ZIP_DEFLATED) as zout:
        for name, data in files.items():
            zout.writestr(name, data)


def main() -> None:
    parser = argparse.ArgumentParser(description="Fill HW3 report placeholders from summary.txt")
    parser.add_argument("docx_path", help="Path to HW3_Complete_Report.docx")
    parser.add_argument("summary_path", help="Path to summary.txt generated by vad_voiced_unvoiced.py")
    args = parser.parse_args()

    docx_path = Path(args.docx_path)
    summary_path = Path(args.summary_path)

    values = parse_summary(summary_path)
    required = [
        'Original duration (s)',
        'Shortened duration (s)',
        'Removed duration (s)',
        'Compression ratio (%)',
    ]
    missing = [key for key in required if key not in values]
    if missing:
        raise SystemExit(f'Missing keys in summary.txt: {", ".join(missing)}')

    update_docx(docx_path, values)
    print(f'Updated {docx_path}')


if __name__ == '__main__':
    main()
